grammar.js
src/grammar.json
src/parser.c
test/corpus/line_comment.txt

The grammar was only capturing the hashtag that initiates the comment, but not the rest of the line.

fix: parse whole line of comment

---

grammar.js
src/grammar.json
src/node-types.json
src/parser.c
test/corpus/string_literal.txt

@fdncred I'm making baby steps here. There is much more to string literals, so I'll leave it as a draft for now. Right now, the rule is called `string_literal`, but only considers double-quoted string literals. Do you think we should do something like 
```js
string_literal: $ => choice(
double_quoted_string,
single_quoted_string,
...
```
?

String Literals

---

queries/highlights.scm

Related to #5.
@1Kinoti i really wanted to have the hightlights for *neovim* so i took the [ones from your fork](https://github.com/nushell/tree-sitter-nu/compare/main...1Kinoti:tree-sitter-nu:main) and made these PR :innocent: 
> **Note**
> extra details in the commit bodies
- e579d5b762a38e7796318466e83e39412849fb11: get the raw file from @1Kinoti's fork
- fa9607cdfdc1a25588e0b88075793ab628d51a75: format the file a bit.
i do not know a lot about the syntax but i went with 4 spaces and, i hope, a consistent format across the file :relieved:

FEATURE: add highlights query

---

installation/neovim.md

It's ~/.local/share not ~/.local/state

Fix directory in instructions for neovim

---

grammar.js
src/grammar.json

this pr fixes a precedence issue when parsing a `use` declaration.
before
```nu
use "file.nu" some-cmd
------^------ ----^---
use      pipeline
```
now
```nu
use "file.nu" some-cmd
----------^-----------
use
```
it also allows an optional semicolon at the end of `use`, `def`, `def-env`, `export` and `alias`

fix `use` parsing precedence issue

---

queries/highlights.scm

👋 😊
Shebang lines (`#!/some/binary --etc`) are a distinct type according to the grammar, but currently aren't included in the highlights query.
This change treats them as regular comments for the purpose of highlighting.

Treat shebangs as regular comments in the highlights query

---

installation/neovim.md

each time i update this repo in *neovim* i run the script at the end of the *neovim* installation file and each time i get the following error :laughing: 
```
Error:
× Destination file already exists
╭─[entry #1:10:1]
10 │ mkdir $local
11 │ http get ([$remote $file] | str join "/") | save ($local | path join $file)
·                                                  ─────────────┬────────────
·                                                               ╰── Destination file '/home/amtoine/.local/share/nvim/lazy/nvim-treesitter/queries/nu/highlights.scm' already exists
╰────
help: you can use -f, --force to force overwriting the destination
```
this PR fixes this issue with `save --force` :ok_hand:

FIX: save with force the `hightlights.scm` file in *neovim` installation

---

README.md
installation/helix.md
queries/injections.scm

Add installation instruction for helix editor and mention it in `README.md`.
Add `injections.scm` query to support  `TODO` and `FIXME` highlights in comments (see [PR discussion](https://github.com/helix-editor/helix/pull/7873#discussion_r1287216390)):

Helix support

---

corpus/expr/cell_path.nu
grammar.js
src/grammar.json

Fix parsing when paths contain hyphens or underscores (e.g. `$nu.home-path`, `$env.LAST_EXIT_CODE`).
This fixes highlighting issues when paths contain hyphens or underscores.
Fix #33

Fix parsing of cell path

---

corpus/stmt/const.nu
grammar.js
src/grammar.json

Fix parsing of export const

---

corpus/decl/alias.nu
corpus/expr/subexpr.nu
corpus/pipe/commands.nu
corpus/pipe/pipe.nu
grammar.js
src/grammar.json

Fix #45 , Fix #47 
Under the current rule for parsing of command, whether the command is a subexpression or not, line breaks are allowed between command arguments.
This causes the parser to fail to correctly detect the end of a command or pipeline.
This pr changes the rules to allow line breaks between command arguments only when the command is a subexpression.
After this change, the highlights looks like follows

Fix parsing of command

---

corpus/expr/binary-expr.nu
grammar.js
src/grammar.json

Fix parsing of binary expression

---

corpus/decl/def.nu
corpus/pipe/commands.nu
grammar.js
src/grammar.json

Fix parsing long flag

---

corpus/expr/subexpr.nu
grammar.js
src/grammar.json

Fix parsing of if/else and try/catch in parens

---

corpus/decl/def.nu
grammar.js
src/grammar.json
src/node-types.json

This change makes it possible to parse composite types (e.g. `list<record<key: string>>`, `record<key: list<int>>`)

Change to parse composite types

---

corpus/decl/def.nu
grammar.js
src/grammar.json

Fix #63 
Although there are many available symbols, I added `?` that is actually used [here](https://github.com/nushell/nushell/blob/62272975f2244229099c903ab43322f3db7e8d00/toolkit.nu#L396) and `!` that is likely to be used.

Add symbols to command identifier

---

corpus/expr/closure.nu
corpus/expr/record.nu
grammar.js
src/grammar.json
src/node-types.json

Fix #67 
Fix #16 
Fix #65 
This change makes it possible to parse closure without parameter pipes.
And following types are parsed as record key
- unquoted string contains a hyphen
- number
- variable
- subexpression

Fix parsing of closure and record

---

corpus/expr/closure.nu
corpus/expr/record.nu
grammar.js
src/grammar.json

After #68 , parsing of record fails when the key is same as the keyword (e.g. `error`).
This pr fixes the bug.
Before
After

Fix parsing of records when the key is the same as the keyword

---

corpus/decl/module.nu
corpus/expr/list.nu
grammar.js
src/grammar.json
src/node-types.json

Fix parsing of re-export and unquoted string in list

---

corpus/expr/units.nu
grammar.js
queries/nu/highlights.scm
src/grammar.json
src/node-types.json

Fix parsing of units

---

package.json

This PR adds the tree-sitter query location to the package.json file so that `tree-sitter highlight ts.nu` works.

add query location to package.json

---

corpus/decl/def.nu
grammar.js
queries/nu/highlights.scm
src/grammar.json
src/node-types.json

Fix parsing of def using flags

---

corpus/expr/list.nu
corpus/expr/values.nu
corpus/pipe/commands.nu
grammar.js
src/grammar.json
src/node-types.json

Fix #77 
Fix parsing of special keywords (e.g. `inf`, `nan`) to ignore case.
Add a special keyword `infinity`.
Remove the unused keyword `def-env` that was not removed in the #74 pull request.
Improve parsing of unquoted string.

Fix parsing unquoted

---

corpus/ctrl/match.nu
grammar.js
src/grammar.json
src/node-types.json

Fix #60 
This PR changes the syntax tree of list destrcture pattern.
Before this change, only `[$x ..$y]` is supported as list destrcture pattern.
However, there are various cases (e.g. `[1 ..$x]`, [$x $y ..]).
To support other various cases, this PR changes the way of parsing list destrcture pattern.
Before this change, parsing list destrcture pattern generates different syntax tree from list pattern.
For example, when parsing `match $xs {[$x ..$y] => {}}`, `(val_list)` and `(val_variable)` nodes were not generated under `(match_pattern)` node before this change as follows.
```
(nu_script
(pipeline
(pipe_element
(ctrl_match
(val_variable
(identifier))
(match_arm
(match_pattern
(identifier) ; <-- (val_list) and (val_variable) are not generated
(identifier))
(block))))))
```
After this …

Fix parsing of match pattern

---

corpus/ctrl/match.nu
grammar.js
src/grammar.json
src/node-types.json

Fix to correctly parse following two match patterns
- a short-hand of record pattern (e.g. `{$key}`)
- unquoted string

Fix pasing of match pattern

---

queries/nu/indents.scm

I am pretty new to nu-lang, so the indent rules might not be exhaustive, but I decided to add it here since it was missing.

Add treesitter indent rules

---

grammar.js
package-lock.json
package.json
src/grammar.json
src/node-types.json
test/corpus/ctrl/else.nu
test/corpus/decl/use.nu
test/corpus/pipe/commands.nu

Fix parsing of **use**, **else** & **commands**, by taking into account additional valid syntax.
fixes #83 
fixes #88 
fixes #89 
Split the command rule to accomodate 2 more syntaxes: ``^'ls'`` and ``^()``.
Allow non-block syntax for else (in comparison with if, which can't take anything, but a block).
Allow use to take pipe input.

Fixes to parsing of use, else & commands

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/decl/export-env.nu
test/corpus/expr/closure.nu
test/corpus/expr/list.nu
test/corpus/expr/range.nu
test/corpus/expr/record.nu
test/corpus/expr/subexpr.nu
test/corpus/expr/values.nu
test/corpus/pipe/commands.nu
test/corpus/pipe/pipe.nu
test/corpus/pipe/where.nu
test/corpus/stmt/let.nu
test/corpus/stmt/register.nu

Change the node structure of the record & list bodies to better represent the actual syntax of the language. This fixes some bugs as well as make the syntax more consistent & easier to read.
- TS can't properly detect durantion values in records. It is instead deteced as integer & a command node that create an error:
```nu
{
key: 5sec
}
```
- TS can't properly detect when value & key begins & allow invald syntax with value & key having no space or any separator in between. The following example is considered valid by TS:
```nu
{
key: 1536another_key: 8549
}
```
- Records use a new body structure which manages entries & separators in between. This fixes the separator bugs described above & creates new nodes that can be used for highlighting & indenting.
- Lists also have their structure …

Fix parsing of record & list bodies.

---

queries/nu/indents.scm

Fixes indentation issues for function parameters & pipes stacking indentation. Also provides an alternative indentation to pipes.
There was no indentation provided for function parameters within the [] block. Examples
- before:
```nu
export def function_name [
parameter: type   # Documentation
optional?: type   # Documentation
]: [string -> table] {
```
- now:
```nu
export def function_name [
parameter: type   # Documentation
optional?: type   # Documentation
]: [string -> table] {
```
Sometimes pipes nodes can stack on each other on double (triple & so on) the indentation. This generally happens in this pattern:
```nu
{
cmd
} {
cmd
}
```
This would probably occur most commonly in this scenario:
```nu
if true {
cmd
} else {
cmd
}
```
There isn't a straight forward fix to this, so it goes …

Indent modifications

---

grammar.js

This adds several warning & error suppressions for the tsserver lsp. Doesn't actually change any functionality (if you tree-sitter generate you will see that nothing would get changed).
- add type docs to functions
- supress tsserver errors (they are not actual errors, tsserver just can't properly diagnose the grammar.js)
- add _ to unused arguments

Warning & error suppression for LSP

---

grammar.js
src/grammar.json

The separator node introduced in #94 should use lexical precedence instead of parse precedence. This is a quick fix to that.
Currently I don't know any issues introduced by this, but this could potentially create an issue.

Quickfix for separator token using non-lexical precedence.

---

queries/nu/highlights.scm

This updates:
| Query | Highlight name | Like in... |
|-|-|-|
| Punctuation `:`, `,` | `punctuation.special` | TOML, Bash, JSON, ... |
| Key fields in tables/records | `variable.member` | Go, Zig, V, TOML |
| Returns `->` | `punctuation.special` | Rust |
| Variable `$` | `punctuation.special` | Bash, Awk |
| Variable identifier | `variable` | Bash, Awk, Perl, Fish |
| Shebang | `keyword.directive` | Bash, Awk |
| Built-in types | `type` | Zig et al[^1] |
| Numbers | `number` | Zig, Rust, Python, TOML, Bash, ... |
| Arguments | `variable.parameter` |  Bash[^2] |
| Redirect operator | `operator` | Bash, Fish |
| Redirect destination | `variable.parameter` | Bash |
[^1]: Note that for built-in types, languages like Rust, Python, Go differentiates highlights of built-in types and other types …

nvim queries: Conform to commonly used highlight names

---

queries/nu/highlights.scm

I thought it'd be great to highlight built-in commands differently to custom commands similar to what Nu does in the prompt line. It should be fairly easy to use the oneliner included in the comments on later versions of Nu to update the list.
Reference:
- Bash: https://github.com/nvim-treesitter/nvim-treesitter/blob/b694628cbe513ae8bcf9fb5ac791a73ca3fd5320/runtime/queries/bash/highlights.scm#L169-L176
- Fish: https://github.com/nvim-treesitter/nvim-treesitter/blob/b694628cbe513ae8bcf9fb5ac791a73ca3fd5320/runtime/queries/fish/highlights.scm#L115-L124
Core built-ins are filtered out because they are already specified higher up in the file as keywords.
All commands that aren't in the list are still highlighted with `@function`

nvim queries: Highlight built-in commands

---

queries/nu/highlights.scm

Apologies, in #100 I hadn't realized the where command is special-cased in the parser and hence requires a separate capture to highlight properly. This ensures the `where` command is also highlighted as built-in.

Fix highlight of `where` command as builtin

---

installation/neovim.md

Relates to #107
Technically, this doesn't have to happen on every update to the plugin. But I don't think that lazy has a mechanism to detect only changes to `grammar.js` and `queries/nu/*.scm`
Edit: according to OP of #107, this is the fix.

fix: instructions to install the plugin

---

.gitignore
Cargo.lock
grammar.js
package.json
queries/nu/highlights.scm
src/grammar.json
src/node-types.json
test/corpus/pipe/commands.nu

This PR does three things:
1. highlight `=` in `--long-flag=value` flags (orange in my case)
2. highlight flag identifiers as parameters (blue)
3. highlight string values as strings (green)
Before:
After: 
Do we like these changes?

feat: improve distinction of flags and parameters

---

queries/nu/highlights.scm

Last time, I changed identifiers to @type. Most of the time, this is
fine. But when defining a new command with flag parameters, these can
have types and the same highlighting. So now they are attributes and we
have color distinction in both cases.
Before:
After:
Since we currently don't have attributes (usually annotations), this is a unique hl-group for flag identifiers.

fix: flags again

---

Cargo.toml
grammar.js
src/grammar.json
test/corpus/ctrl/match.nu

New test case of "match" with _ and if condition:
```nu
match $x {
_ if $x == 4 => {},
_ => {}
}
```
It will previously cause parsing error:
```lisp
(nu_script ; [0, 0] - [4, 0]
(ERROR ; [0, 0] - [3, 1]
(val_variable ; [0, 6] - [0, 8]
name: (identifier)) ; [0, 7] - [0, 8]
(val_variable ; [1, 7] - [1, 9]
name: (identifier)) ; [1, 8] - [1, 9]
(val_number) ; [1, 13] - [1, 14]
(ERROR) ; [1, 15] - [1, 16]
(expr_binary ; [1, 18] - [2, 9]
lhs: (val_record) ; [1, 18] - [1, 20]
(ERROR) ; [2, 2] - [2, 5]
rhs: (val_record)))) ; [2, 7] - [2, 9]
```

Fix corner case for ctrl_match with _ and match_guard

---

queries/nu/highlights.scm

In #110, I changed highlights. I accidentally committed `(val_string) @variable.parameter`, which should actually be `@string`.

fix: highlights artifact from flags #110

---

queries/nu/indents.scm

Fixes a problem where a match expression does not begin an indent.
Before:
After:

fix: fix indent in multiline match expression

---

grammar.js
src/grammar.json
test/corpus/pipe/commands.nu

This PR fixes #131  by grouping "+/-" and digits in decimals.
Related test cases in `cmd-026-unquoted-string-with-leading-plus`.

Fix unquoted command args with leading +

---

grammar.js
src/grammar.json
src/node-types.json
src/tree_sitter/alloc.h
test/corpus/expr/list.nu
test/corpus/expr/record.nu

This PR fixes situations where record value is an unquoted string
Also cleaned list_entry rule a little bit since signed numbers, flags and unquoted string start with `+/-` are more easy to distinguish.

Allow unquoted values in val_record

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/ctrl/do.nu
test/corpus/expr/values.nu
test/corpus/stmt/hide.nu

This PR fixed following issues in current grammar:
1. hide-env with flags
2. do + closure + more than one arguments / parenthesized multiline do statement
3. wrong result for multiline `expr_interpolated` (here `bar` should be argument instead of the command head of another pipeline)
4. hide those `"\n"` terminal tokens, which makes it easier for query, also more windows friendly.

Fixed some minor errors

---

installation/neovim.md

The current version of the config doesn't enable highlighting of Nushell code.
ChatGPT suggested the changes. I tested the changes with a freshly installed kickstart.nvim and NvChad, and they seem to be working for me. However, I'm a total noob with nvim.

Update lazy.nvim installation config

---

grammar.js
queries/nu/highlights.scm
src/grammar.json
src/node-types.json
test/corpus/decl/use.nu
test/corpus/expr/cell_path.nu
test/corpus/expr/record.nu
test/corpus/expr/spread-operator.nu
test/corpus/pipe/commands.nu
test/corpus/pipe/redirection.nu

This PR should fix #98, as well as several easy problems mentioned in #142.
I think I should keep each PR focused for better traceability, so the trickier issues related to identifier and parameters are left for later.
- example: `^$"($cmd)"`
- `unquoted` node in `decl_use` renamed to `val_string` to align with `stmt_source`
- cases that should fail now simply tagged with `:error` since we generally don't care where the error occurs

Fix spread operators & redirections

---

grammar.js
queries/nu/highlights.scm
src/grammar.json
src/node-types.json
test/corpus/decl/def.nu
test/corpus/pipe/commands.nu

This PR fixes those parameter/flag related issues in #142

Fix issues with parameters and flags

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/expr/identifier.nu
test/corpus/expr/record.nu

This PR fixes most of the remaining issues related to identifiers as reported in #142 .
```nushell
null
7b
nan
g++
7z
7mss
truee
```
It's still not perfect, nushell handles special characters like `-, #, ., ()` in identifiers very dynamically.
I think this is the time to finally resort to an external scanner for further accuracy.

Fix several issues of identifiers

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/expr/binary-expr.nu
test/corpus/expr/identifier.nu
test/corpus/pipe/env.nu

This PR
1. fix #146 , check the test cases in the new env.nu file, remind me if any format is missing.
2. force whitespace in between of binary expression: `1+1` should be command
3. simplify the unquoted rule with lexical precedence.

Fix single-use env and other fixes

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/ctrl/match.nu
test/corpus/expr/list.nu
test/corpus/expr/record.nu

This PR
1. fixes several corner cases, such as:
```nushell
[,,,]
{
echo : 1
}
```
2. generalizes `general_body_rule` to cover more rules within the same pattern
3. makes anonymous tokens more friendly for topiary to format

Precedence tuning

---

package.json
tree-sitter.json

tree-sitter greeted me with this message:
```
Warning: your package.json's `tree-sitter` field has been automatically migrated to the new `tree-sitter.json` config file
For more information, visit https://tree-sitter.github.io/tree-sitter/creating-parsers
```
In this PR, I want to migrate tree-sitter's config to the new format.

chore: migrate to new tree-sitter.json

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/expr/binary-expr.nu

This PR reverts this trick introduced by #149 :
```js
/**
* group operator and its preceding/succeeding whitespace/newline
* @param {string} opr
* @param {boolean} parenthesized
*/
function operator_with_separator(opr, parenthesized) {
const sep = parenthesized ? choice(/[ \t]/, /\r?\n/) : /[ \t]/;
return alias(token(seq(repeat1(sep), opr, repeat1(sep))), opr);
}
```
It turns out that this will cause unwanted side effects of blurring boundaries of tokens around `binary_expression`:
compared to the ideal result after this PR:
Instead, `cmd_identifier` is tweaked to keep expressions like `1+1` away from being parsed as `binary_expression`.

Reverted: force separator around binary operators

---

src/scanner.c

Hopefully this PR fixes recent reported crashes on discord:
```
woosaaahh — Today at 4:57 AM
Finaaaaaally !!!
After debugging nvim-treesitter, neovim lua code for tree-sitter then hours of manual bisect + compiling neovim, 
I think a found an explanation for my neovim crashes !
This commit is the first one that prevent my Neovim from crashing :
https://github.com/neovim/neovim/commit/664de5ea971440f24e3e7e3618786d01fbca6025
It bumps treesitter dependency from v0.22.6 to v0.23.0.
According this https://github.com/neovim/neovim/blob/release-0.10/cmake.deps/deps.txt#L56 ,
the latest stable release (v0.10.2) still uses treesitter v0.22.6.
My understanding is that all languages grammars/parsers/scanners that use 
treesitter v0.23.0 and more are not compatible with nvim v0.10.2 and below.
So …
```

Fix: remove `lexer->log` calls for better compatibility

---

grammar.js
internal.txt
src/grammar.json
src/node-types.json
test/corpus/ctrl/error.nu
test/corpus/decl/def.nu
test/corpus/expr/binary-expr.nu

This PR fixes:
1. `param_value` before `param_type`, e.g. `--param=value: string`
2. `error make {}` by removing it from internal.txt
3. `val_range` in binary expression, e.g. `1 in 1..3`
4. multiline type signature, e.g.
```nushell
table<
foo: string
>
```

fix: multiline collection type and more

---

grammar.js
src/grammar.json
src/node-types.json

This PR fixes some easy ones of the whitespace issues:
There're other harder cases remaining.
I don't quite get the logic behind, seems like bugs of `tree-sitter` itself to me. The work-around solutions in this PR were found through bisection and try-and-error.

fix: whitespace issues of if/for/error/alias

---

grammar.js
src/grammar.json

Before:
After the fix:
Still, I don't have enough understanding of why it works, any help or explanation is welcome.

fix: whitespaces issue of `overlay use`

---

queries/nu/highlights.scm

The doc comment string of a parameter is actually parsed as a child node
Forgot to check it in #171 .

fix: parameter comment doc highlight

---

grammar.js
queries/nu/highlights.scm
src/grammar.json
test/corpus/pipe/redirection.nu

```scheme
[
"o>>"   "out>>"
"e>>"   "err>>"
"e+o>>" "err+out>>"
"o+e>>" "out+err>>"
"o>|"   "out>|"
"e>|"   "err>|"
"e+o>|" "err+out>|"
"o+e>|" "out+err>|"
] @operator
```
Missing redirection operators added to `highlights.scm`.

feat: highlight more redirection operators

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/ctrl/match.nu

This PR fixes parsing error caused by comma in `_match_pattern_record`:
as well as the extra item of anonymous comma in `_match_pattern_list`:
also renamed `item` into `entry` to align with `list_body`

fix: comma in `_match_pattern_record` and `_match_pattern_list`

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/expr/record.nu

This PR fixes the following parsing error.

fix: allow `val_interpolated` as key in `record_entry`

---

grammar.js
queries/nu/folds.scm
queries/nu/highlights.scm
src/grammar.json
src/node-types.json
test/corpus/decl/attribute.nu

Adds support of https://github.com/nushell/nushell/pull/14906#issuecomment-2652223446 @Bahex
This is a general implementation for all kinds of attributes,
We can discuss whether we need more detailed ones for specific attribute like `example`
And this is a breaking change since it modifies `highlights.scm` and adds a new `folds.scm` file,
I'll update nvim-treesitter latter when we nail down the details.

feat!: attributes

---

grammar.js
src/grammar.json

PoC for #185
reduced to
> 16:#define STATE_COUNT 7389
> 17:#define LARGE_STATE_COUNT 1669
from
> 16:#define STATE_COUNT 7954
> 17:#define LARGE_STATE_COUNT 1749
|rule name | count |
|----------|-------|
|val_range                                | 817|
|expr_binary_parenthesized                | 614|
|shebang_repeat1                          | 537|
|val_table                                | 534|
|_immediate_decimal                       | 474|
|_val_range                               | 374|
|_val_number_decimal                      | 362|
|collection_type                          | 330|
|_val_range_with_end                      | 266|
|expr_binary                              | 210|
|_multiple_types_repeat1                  | 200|
|collection_type_repeat1                  | 189| …

refactor: states count reduction for `val_table`

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/stmt/hide.nu

Fixes parsing error of
```nushell
hide-env FOO BAR
```

fix: hide-env with more than one variable

---

grammar.js
src/grammar.json
test/corpus/stmt/let.nu

Fixes parsing error in this:
```nushell
let x: record<foo-bar: string> = { foo-bar: 'tree-sitter' }
```

fix: id in collection_type should allow hyphen

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/expr/binary-expr.nu

Fixes parsing error of:
```nushell
'foo' like 'bar'
```

fix: like/not-like operator

---

grammar.js
src/grammar.json
test/corpus/expr/closure.nu

Fixes
```nushell
{||}
```
Seems to me that rules for `val_closure`/`val_record`/`block` are delicately balanced in current parser.
That's not very healthy for maintenance. 
Each time I tried to optimize those rules, I ended up breaking some test cases.

fix: empty closure

---

queries/nu/highlights.scm
queries/nu/injections.scm

- refactor: simplify queries and reformat
- feat: arbitrary language injection: 
- allow additional formatting with `@string.code`

improve language injections

---

queries/nu/highlights.scm

I don't know really know the performance characteristics of tree-sitter queries (nor how to benchmark them), so while just using a wildcard was my first instinct, I used an explicit where_predicate node.
Would this be better or worse?
```tree-sitter-query
(_
opr: _ @operator)
```

fix(highlight): highlight operators in where predicates

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/pipe/env.nu

Fixes the parsing error described in https://github.com/blindFS/topiary-nushell/issues/20
Known difference to native nu-parser after the fix:`FOO=(bar) baz` 
1. error by tree-sitter-nu.
2. assign a string of `'(bar)'` (with the parentheses) to env variable `FOO` in nu
I guess that's a corner case nobody actually cares.

fix: env_var with (interpolated) string as value
